# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'project1_2.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import os
import json
import shutil
import numpy as np
from PIL import Image
import sys
import cv2 as cv
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow, QMessageBox, QWidget, QDialogButtonBox,QApplication, QMainWindow, QFileDialog,
from PyQt5.QtGui import QPixmap, QImage, QDesktopServices
from PyQt5.QtCore import Qt
from PyQt5.QtCore import QBuffer, QIODevice, QUrl
import cv2
import RecognitionFreshTobacco
import RecognitionCuringTobacco
import RecognitionFluedTobacco
from RgbHistogram import rgbCurve
